### ISSUE TITLE
OCR Engine Support: Pororo (`kakaobrain/pororo`, potentially used together with EasyOCR)

### ISSUE THREAD

**Issue by junhoyeo** [junhoyeo/BetterOCR#2]
- https://x.com/alstjr7375/status/1718187842902569405
- https://github.com/black7375/korean_ocr_using_pororo/commit/a6490a032accfbf7d00ca03ad1a19ac8fba6b3fb
- https://github.com/kakaobrain/pororo
- Kudos to @black7375 for suggesting 👍

**Comment by black7375** [comment]
To summarize the tweet again, (Currently, `X` can't see the list of answers without login)

1. [EasyOCR](https://github.com/JaidedAI/EasyOCR) is excellent in text detection.
2. [Pororo](https://github.com/kakaobrain/pororo) is superior to EasyOCR in text recognition.
   - But Pororo is still good at [English and Korean](https://kakaobrain.github.io/pororo/miscs/ocr.html).
3. Pre-processing is another way to increase the recognition rate, and the application method must also vary depending on the characteristics of the OCR engine.
   - For example, [below v3.05 of Tesseract](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#inverting-images) is advantageous for dark backgrounds, but after `v4.0` that it is advantageous for bright backgrounds.
   - Technologies such as normalization, binarization, and skeletonization may be good in document images, but they are not suitable for photographic images. (Shades of small letters become clumpy and indistinguishable with high probability)
   - One of the few pretreatment that works well with most OCR engines is grayscale.
   - If the size of the ROI(region of interest) is too small, it is [better to scale up](https://github.com/black7375/korean_ocr_using_pororo/blob/35496c4b303b5af0010954be81765dd341c6f2df/utils/pre_processing.py#L96-L100).
   - I am convinced that the Tesseract's OSD(Orientation and script detection),[estimate perspective transformations](https://mzucker.github.io/2016/10/11/unprojecting-text-with-ellipses.html) or [dewarping](https://mzucker.github.io/2016/08/15/page-dewarping.html) will improve performance.
     However, it is expected to be difficult to apply only when detecting and appropriate.
     The easy way is to apply to each ROI.
